Repository Lotte-BossBabies/Boss-Book-Project, pull requests merged in 2022-07, with the labels that each got.

#2 fix: Project - AWS RDS MySQL connection error fix #1
  pom.xml
  src/main/java/bossbabies/com/a/HelloServlet.java
  src/main/java/bossbabies/com/a/controller/TestController.java
  src/main/java/bossbabies/com/a/dao/TestDao.java
  src/main/java/bossbabies/com/a/dao/TestDaoImpl.java
  src/main/java/bossbabies/com/a/dto/TestDto.java
  src/main/java/bossbabies/com/a/service/TestService.java
  src/main/resources/sqls/Text.xml
  src/main/resources/sqls/test.xml
  src/main/webapp/WEB-INF/spring/servlet-context.xml
  src/main/webapp/WEB-INF/views/test.jsp
  src/main/webapp/index.jsp
  src/test/db/DBTest.java
Labels: hotfix🚨

#7 feat: 도서 api 파싱 및 삽입 구현(#5)
  .gitignore
  pom.xml
  src/main/java/bossbabies/com/a/controller/BookApiController.java
  src/main/java/bossbabies/com/a/dao/BookApiDao.java
  src/main/java/bossbabies/com/a/dao/BookApiDaoImpl.java
  src/main/java/bossbabies/com/a/dto/BookDto.java
  src/main/java/bossbabies/com/a/service/BookApiService.java
  src/main/java/bossbabies/com/a/service/BookApiServiceImpl.java
  src/main/resources/sqls/Text.xml
  src/main/resources/sqls/api.xml
  src/main/webapp/WEB-INF/spring/applicationContext.xml
  src/main/webapp/WEB-INF/spring/servlet-context.xml
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/index.jsp
Labels: feat🎈, fix👾

#16 feat: 관리자 페이지 기능 초기 구현
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDao.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDaoImpl.java
  src/main/java/bossbabies/com/a/dao/test/TestDao.java
  src/main/java/bossbabies/com/a/dao/test/TestDaoImpl.java
  src/main/java/bossbabies/com/a/dto/RegisteredBookDto.java
  src/main/java/bossbabies/com/a/parameterVO/CategoryAndKeywordVO.java
  src/main/java/bossbabies/com/a/parameterVO/IdAndCountVO.java
  src/main/java/bossbabies/com/a/parameterVO/StatusAndRegisteredBookIdVO.java
  src/main/java/bossbabies/com/a/service/TestService.java
  src/main/resources/sqls/registeredBook.xml
  src/test/db/DBTest.java
  src/test/sql/registeredBookTest.java
Labels: feat🎈, test🔧

#19 test: Test용 Controller, Service, Dao, Dto 삭제
  src/main/java/bossbabies/com/a/controller/TestController.java
  src/main/java/bossbabies/com/a/dao/test/TestDao.java
  src/main/java/bossbabies/com/a/dao/test/TestDaoImpl.java
  src/main/java/bossbabies/com/a/dto/TestDto.java
  src/main/java/bossbabies/com/a/service/TestService.java
Labels: temp👽

#20 temp : test.jsp 삭제
  src/main/webapp/WEB-INF/views/test.jsp
Labels: temp👽

#15 상세 페이지 정보 출력 #11
  src/main/java/bossbabies/com/a/controller/DetailedBookController.java
  src/main/java/bossbabies/com/a/dao/BookDao.java
  src/main/java/bossbabies/com/a/dao/BookDaoImpl.java
  src/main/java/bossbabies/com/a/dao/LikesDao.java
  src/main/java/bossbabies/com/a/dao/LikesDaoImpl.java
  src/main/java/bossbabies/com/a/dao/RegisteredBookDao.java
  src/main/java/bossbabies/com/a/dao/RegisteredBookDaoImpl.java
  src/main/java/bossbabies/com/a/dto/BookDto.java
  src/main/java/bossbabies/com/a/dto/LikesDto.java
  src/main/java/bossbabies/com/a/dto/RegisteredBookDto.java
  src/main/java/bossbabies/com/a/service/DetailedBookService.java
  src/main/java/bossbabies/com/a/service/DetailedBookServiceImpl.java
  src/main/resources/sqls/book.xml
  src/main/resources/sqls/likes.xml
  src/main/resources/sqls/registered_book.xml
  src/main/webapp/WEB-INF/views/book/detailedBook.jsp
Labels: feat🎈

#21 feat: 마이페이지 기능 구현
  src/main/java/bossbabies/com/a/controller/MyPageController.java
  src/main/java/bossbabies/com/a/dao/MyPageDao.java
  src/main/java/bossbabies/com/a/dto/LikedBookDto.java
  src/main/java/bossbabies/com/a/dto/MyPageDto.java
  src/main/java/bossbabies/com/a/dto/OrderDto.java
  src/main/java/bossbabies/com/a/dto/OrderedBookDto.java
  src/main/java/bossbabies/com/a/service/MyPageService.java
  src/main/resources/sqls/MyPage.xml
  src/main/webapp/WEB-INF/spring/servlet-context.xml
  src/main/webapp/WEB-INF/views/MyPage.jsp
  src/main/webapp/WEB-INF/views/bookDetail.jsp
  src/main/webapp/index.jsp
Labels: feat🎈

#26 feat: myPage 주문 취소, 좋아요 취소 기능 추가
  src/main/java/bossbabies/com/a/controller/MyPageController.java
  src/main/java/bossbabies/com/a/dao/likes/LikesDao.java
  src/main/java/bossbabies/com/a/dao/likes/LikesDaoImpl.java
  src/main/java/bossbabies/com/a/dao/mypage/MyPageDao.java
  src/main/java/bossbabies/com/a/dto/mypage/LikedBookDto.java
  src/main/java/bossbabies/com/a/dto/mypage/MyPageDto.java
  src/main/java/bossbabies/com/a/dto/mypage/OrderedBookDto.java
  src/main/java/bossbabies/com/a/service/MyPageService.java
  src/main/resources/sqls/likes.xml
  src/main/resources/sqls/myPage.xml
  src/main/webapp/WEB-INF/views/myPage.jsp
Labels: feat🎈, style🌈

#28 feat: member 회원가입 구현 #27
  src/main/java/bossbabies/com/a/controller/MainController.java
  src/main/java/bossbabies/com/a/controller/UserController.java
  src/main/java/bossbabies/com/a/dao/user/MemberDao.java
  src/main/java/bossbabies/com/a/dao/user/MemberDaoImpl.java
  src/main/java/bossbabies/com/a/dao/user/SellerDao.java
  src/main/java/bossbabies/com/a/dao/user/SellerDaoImpl.java
  src/main/java/bossbabies/com/a/dto/user/MemberDto.java
  src/main/java/bossbabies/com/a/dto/user/SellerDto.java
  src/main/java/bossbabies/com/a/service/MemberService.java
  src/main/java/bossbabies/com/a/service/MemberServiceImpl.java
  src/main/java/bossbabies/com/a/service/SellerService.java
  src/main/java/bossbabies/com/a/service/SellerServiceImpl.java
  src/main/java/bossbabies/com/a/service/UserService.java
  src/main/java/bossbabies/com/a/service/UserServiceImpl.java
  src/main/resources/sqls/member.xml
  src/main/resources/sqls/seller.xml
  src/main/webapp/WEB-INF/views/user/memberRegi.jsp
  src/main/webapp/WEB-INF/views/user/memberRegiAf.jsp
  src/main/webapp/WEB-INF/views/user/userSelect.jsp
  src/main/webapp/index.jsp
Labels: feat🎈

#31 feat: 마이페이지 - 리뷰 작성
  src/main/java/bossbabies/com/a/controller/MyPageController.java
  src/main/java/bossbabies/com/a/dao/mypage/MyPageDao.java
  src/main/java/bossbabies/com/a/dto/mypage/ReviewDto.java
  src/main/java/bossbabies/com/a/parameterVO/ReviewVO.java
  src/main/java/bossbabies/com/a/service/MyPageService.java
  src/main/resources/sqls/myPage.xml
  src/main/webapp/WEB-INF/views/myPage.jsp
  src/main/webapp/WEB-INF/views/writeReview.jsp
Labels: feat🎈, fix👾

#34 feat: 메인 페이지 페이지 디자인 구현 #14
  src/main/webapp/WEB-INF/views/book/main.jsp
  src/main/webapp/resources/css/banner.css
  src/main/webapp/resources/css/footer.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/images/logo.png
Labels: feat🎈

#37 feat: Admin Page 기능 백엔드, 프론트엔드 구현 #3 #4 #6
  src/main/java/bossbabies/com/a/controller/AdminController.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDao.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDaoImpl.java
  src/main/java/bossbabies/com/a/dto/RegisteredBookDto.java
  src/main/java/bossbabies/com/a/parameterVO/CategoryAndKeywordVO.java
  src/main/java/bossbabies/com/a/parameterVO/SellerAndCategoryVO.java
  src/main/java/bossbabies/com/a/service/admin/AdminService.java
  src/main/java/bossbabies/com/a/service/admin/AdminServiceImpl.java
  src/main/resources/sqls/registeredBook.xml
  src/main/webapp/WEB-INF/views/admin/books.jsp
  src/main/webapp/resources/css/adminMain.css
  src/main/webapp/resources/js/admin.js
  src/test/service/AdminServiceTest.java
  src/test/sql/RegisteredBookTest.java
Labels: feat🎈

#39 Feat: 메인페이지 추천도서, 인기도서 기능 구현 #38
  src/main/java/bossbabies/com/a/controller/MainController.java
  src/main/java/bossbabies/com/a/dao/book/BookDao.java
  src/main/java/bossbabies/com/a/dao/book/BookDaoImpl.java
  src/main/java/bossbabies/com/a/dto/BookDto.java
  src/main/java/bossbabies/com/a/dto/main/RegisteredBookInfoDto.java
  src/main/java/bossbabies/com/a/service/BookInfoService.java
  src/main/java/bossbabies/com/a/service/BookInfoServiceImpl.java
  src/main/resources/sqls/book.xml
  src/main/webapp/WEB-INF/views/book/main.jsp
Labels: feat🎈

#41 feat: 회원, 판매자 정보수정, 카카오 로그인 구현
  src/main/java/bossbabies/com/a/controller/UserController.java
  src/main/java/bossbabies/com/a/dao/user/MemberDao.java
  src/main/java/bossbabies/com/a/dao/user/MemberDaoImpl.java
  src/main/java/bossbabies/com/a/dao/user/SellerDao.java
  src/main/java/bossbabies/com/a/dao/user/SellerDaoImpl.java
  src/main/java/bossbabies/com/a/parameterVO/UpdateMemberVO.java
  src/main/java/bossbabies/com/a/parameterVO/UpdateSellerVO.java
  src/main/java/bossbabies/com/a/service/MemberService.java
  src/main/java/bossbabies/com/a/service/MemberServiceImpl.java
  src/main/java/bossbabies/com/a/service/SellerService.java
  src/main/java/bossbabies/com/a/service/SellerServiceImpl.java
  src/main/resources/sqls/member.xml
  src/main/resources/sqls/seller.xml
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/WEB-INF/views/user/updateMember.jsp
  src/main/webapp/WEB-INF/views/user/updateSeller.jsp
  src/main/webapp/index.jsp
Labels: feat🎈

#42 fix: 마이페이지 수정
  src/main/java/bossbabies/com/a/controller/MyPageController.java
  src/main/java/bossbabies/com/a/dao/mypage/MyPageDao.java
  src/main/java/bossbabies/com/a/dto/mypage/LikedBookDto.java
  src/main/java/bossbabies/com/a/dto/mypage/MyPageReviewDto.java
  src/main/java/bossbabies/com/a/dto/mypage/OrderedBookDto.java
  src/main/java/bossbabies/com/a/service/MyPageService.java
  src/main/resources/sqls/myPage.xml
  src/main/resources/sqls/review.xml
  src/main/webapp/WEB-INF/views/myPage.jsp
Labels: feat🎈, fix👾, style🌈

#43 refactor: header,footer,main jsp 분리 작업
  src/main/java/bossbabies/com/a/controller/MainController.java
  src/main/webapp/WEB-INF/views/book/bookstore.jsp
  src/main/webapp/WEB-INF/views/book/main.jsp
  src/main/webapp/WEB-INF/views/book/mainpage.jsp
  src/main/webapp/WEB-INF/views/layout/banner.jsp
  src/main/webapp/WEB-INF/views/layout/footer.jsp
  src/main/webapp/WEB-INF/views/layout/header.jsp
  src/main/webapp/WEB-INF/views/layout/main.jsp
  src/main/webapp/resources/css/banner.css
  src/main/webapp/resources/css/footer.css
  src/main/webapp/resources/css/header.css
Labels: refactor

#44 feat: 마이페이지 CSS
  src/main/java/bossbabies/com/a/controller/MyPageController.java
  src/main/java/bossbabies/com/a/dao/book/BookDao.java
  src/main/java/bossbabies/com/a/dao/book/BookDaoImpl.java
  src/main/java/bossbabies/com/a/service/DetailedBookService.java
  src/main/java/bossbabies/com/a/service/DetailedBookServiceImpl.java
  src/main/resources/sqls/book.xml
  src/main/webapp/WEB-INF/views/myPage.jsp
  src/main/webapp/WEB-INF/views/writeReview.jsp
  src/main/webapp/resources/images/document.png
  src/main/webapp/resources/images/happiness.png
Labels: feat🎈, style🌈

#49 feat : kakao 회원가입, 아이디찾기, 비밀번호찾기 구현
  src/main/java/bossbabies/com/a/controller/KakaoController.java
  src/main/java/bossbabies/com/a/controller/UserController.java
  src/main/java/bossbabies/com/a/dao/user/MemberDao.java
  src/main/java/bossbabies/com/a/dao/user/MemberDaoImpl.java
  src/main/java/bossbabies/com/a/dao/user/SellerDao.java
  src/main/java/bossbabies/com/a/dao/user/SellerDaoImpl.java
  src/main/java/bossbabies/com/a/parameterVO/FindIdVO.java
  src/main/java/bossbabies/com/a/parameterVO/FindPasswordVO.java
  src/main/java/bossbabies/com/a/service/KakaoService.java
  src/main/java/bossbabies/com/a/service/MemberService.java
  src/main/java/bossbabies/com/a/service/MemberServiceImpl.java
  src/main/java/bossbabies/com/a/service/SellerService.java
  src/main/java/bossbabies/com/a/service/SellerServiceImpl.java
  src/main/resources/sqls/member.xml
  src/main/resources/sqls/seller.xml
  src/main/webapp/WEB-INF/views/user/findId.jsp
  src/main/webapp/WEB-INF/views/user/findIdOk.jsp
  src/main/webapp/WEB-INF/views/user/findPassword.jsp
  src/main/webapp/WEB-INF/views/user/findPasswordOk.jsp
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/WEB-INF/views/user/memberRegi.jsp
  src/main/webapp/WEB-INF/views/user/sellerRegi.jsp
  src/main/webapp/WEB-INF/views/user/userSelect.jsp
  src/main/webapp/resources/css/register.css
  src/main/webapp/resources/images/left.png
  src/main/webapp/resources/images/right.png
Labels: feat🎈

#52 feat: 관리자 페이지 - 메인, 상품 수정, 상품 등록 페이지 기능 구현
  src/main/java/bossbabies/com/a/controller/AdminController.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDao.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDaoImpl.java
  src/main/java/bossbabies/com/a/dto/RegisteredBookDto.java
  src/main/java/bossbabies/com/a/parameterVO/CategoryAndKeywordVO.java
  src/main/java/bossbabies/com/a/parameterVO/IdAndCountVO.java
  src/main/java/bossbabies/com/a/parameterVO/SellerAndCategoryVO.java
  src/main/java/bossbabies/com/a/service/admin/AdminService.java
  src/main/java/bossbabies/com/a/service/admin/AdminServiceImpl.java
  src/main/resources/sqls/registeredBook.xml
  src/main/webapp/WEB-INF/views/admin/bookEdit.jsp
  src/main/webapp/WEB-INF/views/admin/bookRegister.jsp
  src/main/webapp/WEB-INF/views/admin/books.jsp
  src/main/webapp/resources/js/admin.js
  src/main/webapp/resources/js/adminRegister.js
  src/test/db/DBTest.java
  src/test/service/AdminServiceTest.java
  src/test/sql/RegisteredBookTest.java
Labels: feat🎈, fix👾, test🔧

#53 fix: 통계 페이지, 차트 수정
  pom.xml
  src/main/java/bossbabies/com/a/controller/AvgController.java
  src/main/java/bossbabies/com/a/dao/avg/AvgDao.java
  src/main/java/bossbabies/com/a/dto/avg/CategorySaleRateDto.java
  src/main/java/bossbabies/com/a/dto/avg/SalesByPeriodDto.java
  src/main/java/bossbabies/com/a/service/AvgService.java
  src/main/resources/sqls/avg.xml
  src/main/webapp/WEB-INF/views/avg.jsp
Labels: fix👾

#56 hotfix : merge 오류 수정
  src/main/java/bossbabies/com/a/controller/AdminController.java
  src/main/java/bossbabies/com/a/controller/MainController.java
  src/main/java/bossbabies/com/a/dto/RegisteredBookDto.java
  src/main/java/bossbabies/com/a/parameterVO/CategoryAndKeywordVO.java
Labels: hotfix🚨

#57 feat: 아이디 중복체크 기능구현
  src/main/java/bossbabies/com/a/controller/UserController.java
  src/main/java/bossbabies/com/a/dao/user/MemberDao.java
  src/main/java/bossbabies/com/a/dao/user/MemberDaoImpl.java
  src/main/java/bossbabies/com/a/dao/user/SellerDao.java
  src/main/java/bossbabies/com/a/dao/user/SellerDaoImpl.java
  src/main/java/bossbabies/com/a/service/MemberService.java
  src/main/java/bossbabies/com/a/service/MemberServiceImpl.java
  src/main/java/bossbabies/com/a/service/SellerService.java
  src/main/java/bossbabies/com/a/service/SellerServiceImpl.java
  src/main/resources/sqls/member.xml
  src/main/resources/sqls/seller.xml
  src/main/webapp/WEB-INF/views/user/memberRegi.jsp
  src/main/webapp/WEB-INF/views/user/sellerRegi.jsp
Labels: feat🎈

#58 feat: 리뷰 삭제 기능
  src/main/java/bossbabies/com/a/controller/MyPageController.java
  src/main/java/bossbabies/com/a/dao/mypage/MyPageDao.java
  src/main/java/bossbabies/com/a/dao/mypage/MyPageDaoImpl.java
  src/main/java/bossbabies/com/a/dto/mypage/MyPageReviewDto.java
  src/main/java/bossbabies/com/a/service/MyPageService.java
  src/main/java/bossbabies/com/a/service/MyPageServiceImpl.java
  src/main/resources/sqls/review.xml
  src/main/webapp/WEB-INF/views/myPage.jsp
Labels: feat🎈

#60 feat: 세션값 추가
  src/main/java/bossbabies/com/a/controller/UserController.java
  src/main/webapp/WEB-INF/views/user/temp.jsp
Labels: fix👾

#62 feat: 세션값 member_id, seller_id 추가
  src/main/java/bossbabies/com/a/controller/UserController.java
  src/main/java/bossbabies/com/a/dto/user/SellerDto.java
  src/main/resources/sqls/member.xml
  src/main/resources/sqls/seller.xml
Labels: fix👾

#63 feat: Test Page 삭제 및 리다이렉트
  src/main/webapp/WEB-INF/views/user/temp.jsp
Labels: fix👾

#64 feat: redirect 버그 fix
  src/main/java/bossbabies/com/a/controller/UserController.java
Labels: fix👾

#65 feat: commit 확인
  src/main/java/bossbabies/com/a/controller/UserController.java
Labels: temp👽

#66 상세페이지&관리자배송관리페이지 css 파일 분리 #54
  src/main/webapp/WEB-INF/views/admin/manageDelivery.jsp
  src/main/webapp/WEB-INF/views/book/detailedBook.jsp
  src/main/webapp/WEB-INF/views/book/orderResult.jsp
  src/main/webapp/resources/css/detailedBook.css
  src/main/webapp/resources/css/manageDelivery.css
  src/main/webapp/resources/css/orderResult.css
Labels: feat🎈, style🌈

#68 feat: 마이페이지-세션, 개인 정보 수정
  src/main/java/bossbabies/com/a/controller/MyPageController.java
  src/main/java/bossbabies/com/a/controller/UserController.java
  src/main/webapp/WEB-INF/views/myPage.jsp
Labels: feat🎈, fix👾

#71 feat: header - 로그인&로그아웃 구현
  src/main/java/bossbabies/com/a/controller/UserController.java
  src/main/webapp/WEB-INF/views/layout/header.jsp
Labels: feat🎈

#72 상세페이지 세션 연결 추가 #70
  src/main/java/bossbabies/com/a/controller/DetailedBookController.java
  src/main/java/bossbabies/com/a/service/DetailedBookServiceImpl.java
  src/main/webapp/WEB-INF/views/book/detailedBook.jsp
  src/main/webapp/WEB-INF/views/book/orderResult.jsp
  src/main/webapp/resources/css/detailedBook.css
  src/main/webapp/resources/css/orderResult.css
Labels: feat🎈

#74 feat: 관리자 페이지 - 상품 등록 기능 추가 구현
  src/main/java/bossbabies/com/a/controller/AdminController.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDao.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDaoImpl.java
  src/main/java/bossbabies/com/a/service/admin/AdminService.java
  src/main/java/bossbabies/com/a/service/admin/AdminServiceImpl.java
  src/main/resources/sqls/registeredBook.xml
  src/main/webapp/WEB-INF/views/admin/bookRegister.jsp
  src/main/webapp/WEB-INF/views/admin/books.jsp
  src/main/webapp/resources/css/adminMain.css
  src/main/webapp/resources/js/admin.js
  src/main/webapp/resources/js/adminRegister.js
Labels: feat🎈

#75 feat: 회원가입 css 수정
  src/main/webapp/WEB-INF/views/user/memberRegi.jsp
  src/main/webapp/WEB-INF/views/user/sellerRegi.jsp
  src/main/webapp/resources/css/formPage.css
  src/main/webapp/resources/css/style.css
Labels: fix👾

#76 feat: 회원정보 null 버그 fix 및login css 조정
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/WEB-INF/views/user/memberRegi.jsp
  src/main/webapp/WEB-INF/views/user/sellerRegi.jsp
  src/main/webapp/resources/css/style.css
Labels: fix👾

#79 Feat/main header
  src/main/webapp/WEB-INF/views/layout/header.jsp
  src/main/webapp/WEB-INF/views/myPage.jsp
  src/main/webapp/WEB-INF/views/user/memberRegi.jsp
  src/main/webapp/WEB-INF/views/user/sellerRegi.jsp
  src/main/webapp/WEB-INF/views/user/updateMember.jsp
  src/main/webapp/WEB-INF/views/user/updateSeller.jsp
  src/main/webapp/WEB-INF/views/user/userSelect.jsp
Labels: feat🎈

#81 관리자 페이지 레이아웃 UI 적용 및 전체 카테고리 검색 기능 추가 #80
  src/main/java/bossbabies/com/a/controller/AdminController.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDao.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDaoImpl.java
  src/main/java/bossbabies/com/a/service/admin/AdminServiceImpl.java
  src/main/resources/sqls/registeredBook.xml
  src/main/webapp/WEB-INF/views/admin/books.jsp
  src/main/webapp/resources/css/adminMain.css
Labels: feat🎈

#82 feat: id 저장버그 fix 및 user관련 css 변경
  src/main/webapp/WEB-INF/views/user/findId.jsp
  src/main/webapp/WEB-INF/views/user/findIdOk.jsp
  src/main/webapp/WEB-INF/views/user/findPassword.jsp
  src/main/webapp/WEB-INF/views/user/findPasswordOk.jsp
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/WEB-INF/views/user/memberRegi.jsp
  src/main/webapp/WEB-INF/views/user/sellerRegi.jsp
  src/main/webapp/WEB-INF/views/user/updateMember.jsp
  src/main/webapp/WEB-INF/views/user/updateSeller.jsp
  src/main/webapp/resources/css/formPage.css
  src/main/webapp/resources/css/register.css
  src/main/webapp/resources/css/style.css
  src/main/webapp/resources/css/userupdate.css
  src/main/webapp/resources/js/login.js
Labels: fix👾

#83 feat: 관리자 페이지 - 상품 등록 페이지, 상품 등록 상세 페이지 구현
  src/main/java/bossbabies/com/a/controller/AdminController.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDao.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDaoImpl.java
  src/main/java/bossbabies/com/a/parameterVO/BookAndSellerVO.java
  src/main/java/bossbabies/com/a/parameterVO/RegisterBookVO.java
  src/main/java/bossbabies/com/a/service/admin/AdminService.java
  src/main/java/bossbabies/com/a/service/admin/AdminServiceImpl.java
  src/main/resources/sqls/registeredBook.xml
  src/main/webapp/WEB-INF/views/admin/bookRegisterDetail.jsp
  src/main/webapp/WEB-INF/views/admin/books.jsp
  src/main/webapp/resources/js/admin.js
  src/main/webapp/resources/js/adminRegister.js
Labels: feat🎈, fix👾, refactor

#85 feat: 보스베이비 멤버들 소개 추가
  src/main/java/bossbabies/com/a/controller/AvgController.java
  src/main/webapp/WEB-INF/views/avg.jsp
  src/main/webapp/WEB-INF/views/bossbabies.jsp
  src/main/webapp/resources/images/CY.png
  src/main/webapp/resources/images/ES.png
  src/main/webapp/resources/images/GJ.png
  src/main/webapp/resources/images/HY.png
  src/main/webapp/resources/images/MJ.png
  src/main/webapp/resources/images/YW.png
Labels: feat🎈

#86 feat: main과 소개페이지 link
  src/main/webapp/WEB-INF/views/layout/header.jsp
Labels: feat🎈

#88 관리자 상품등록 페이지&관리자 정보 수정 페이지 레이아웃 및 UI #87
  src/main/java/bossbabies/com/a/controller/AdminController.java
  src/main/webapp/WEB-INF/views/admin/bookRegister.jsp
  src/main/webapp/WEB-INF/views/admin/books.jsp
  src/main/webapp/WEB-INF/views/admin/manageDelivery.jsp
  src/main/webapp/WEB-INF/views/user/updateMember.jsp
  src/main/webapp/WEB-INF/views/user/updateSeller.jsp
  src/main/webapp/resources/css/adminMain.css
  src/main/webapp/resources/css/manageDelivery.css
Labels: feat🎈

#89 fix: 소개 페이지 header, footer 추가
  src/main/webapp/WEB-INF/views/bossbabies.jsp
Labels: fix👾

#91 관리자 페이지 오류 수정
  src/main/java/bossbabies/com/a/controller/AdminController.java
Labels: fix👾

#93 style: 마이페이지 css
  src/main/webapp/WEB-INF/views/bossbabies.jsp
  src/main/webapp/WEB-INF/views/myPage.jsp
  src/main/webapp/WEB-INF/views/user/findPassword.jsp
  src/main/webapp/WEB-INF/views/writeReview.jsp
Labels: style🌈

#94 feat: 관리자 상품 조회 페이지 - 주문 수량, 전체 수량 표기 추가
  src/main/webapp/WEB-INF/views/admin/books.jsp
  src/main/webapp/resources/js/admin.js
Labels: feat🎈

#96 개인정보수정 및 상세페이지 css 수정
  src/main/webapp/WEB-INF/views/admin/manageDelivery.jsp
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/WEB-INF/views/user/updateMember.jsp
  src/main/webapp/WEB-INF/views/user/updateSeller.jsp
  src/main/webapp/resources/css/detailedBook.css
  src/main/webapp/resources/css/footer.css
  src/main/webapp/resources/css/formPage.css
  src/main/webapp/resources/css/style.css
  src/main/webapp/resources/css/userupdate.css
Labels: refactor

#97 style: 마이페이지 css
  src/main/webapp/WEB-INF/views/myPage.jsp
Labels: style🌈

#99 관리자 상품 등록 페이지에서 전체 카테고리 추가 #98
  src/main/java/bossbabies/com/a/controller/AdminController.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDao.java
  src/main/java/bossbabies/com/a/dao/registeredBook/RegisteredBookDaoImpl.java
  src/main/java/bossbabies/com/a/service/admin/AdminServiceImpl.java
  src/main/resources/sqls/registeredBook.xml
  src/main/webapp/WEB-INF/views/admin/bookRegister.jsp
Labels: feat🎈

#103 style: 관리자 메인, 상품 등록 페이지 div 간격 및 불필요 주석 삭제
  src/main/webapp/WEB-INF/views/admin/bookRegister.jsp
  src/main/webapp/resources/css/adminMain.css
  src/main/webapp/resources/css/bookRegister.css
Labels: style🌈

#104 fix: 회원가입 css 수정
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/WEB-INF/views/user/memberRegi.jsp
  src/main/webapp/WEB-INF/views/user/sellerRegi.jsp
Labels: fix👾

#106 fix: 마이페이지 css 및 경로 수정
  src/main/java/bossbabies/com/a/controller/UserController.java
  src/main/webapp/WEB-INF/views/bossbabies.jsp
  src/main/webapp/WEB-INF/views/myPage.jsp
Labels: fix👾, style🌈

#108 구매 확인 페이지 추가
  src/main/java/bossbabies/com/a/controller/DetailedBookController.java
  src/main/java/bossbabies/com/a/dao/user/SellerDao.java
  src/main/java/bossbabies/com/a/dao/user/SellerDaoImpl.java
  src/main/java/bossbabies/com/a/service/DetailedBookService.java
  src/main/java/bossbabies/com/a/service/DetailedBookServiceImpl.java
  src/main/resources/sqls/registeredBook.xml
  src/main/resources/sqls/seller.xml
  src/main/webapp/WEB-INF/views/book/checkOrder.jsp
  src/main/webapp/WEB-INF/views/book/detailedBook.jsp
  src/main/webapp/resources/css/checkOrder.css
Labels: feat🎈

#110 feat: css 수정 및 post 방식 변경
  src/main/java/bossbabies/com/a/controller/UserController.java
  src/main/webapp/WEB-INF/views/layout/header.jsp
  src/main/webapp/WEB-INF/views/user/findId.jsp
  src/main/webapp/WEB-INF/views/user/findIdOk.jsp
  src/main/webapp/WEB-INF/views/user/findPassword.jsp
  src/main/webapp/WEB-INF/views/user/findPasswordOk.jsp
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/WEB-INF/views/user/memberRegi.jsp
  src/main/webapp/WEB-INF/views/user/sellerRegi.jsp
  src/main/webapp/WEB-INF/views/user/updateMember.jsp
  src/main/webapp/WEB-INF/views/user/updateSeller.jsp
  src/main/webapp/WEB-INF/views/user/userSelect.jsp
  src/main/webapp/resources/css/findResultPage.css
  src/main/webapp/resources/css/formPage.css
  src/main/webapp/resources/js/post.js
Labels: fix👾, refactor

#111 feat: bug fix
  src/main/webapp/WEB-INF/views/myPage.jsp
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/resources/js/post.js
Labels: fix👾

#112 feat: seller bug fix
  src/main/webapp/WEB-INF/views/admin/books.jsp
Labels: fix👾

#118 feat: 도서구매 css fix
  src/main/webapp/WEB-INF/views/book/checkOrder.jsp
  src/main/webapp/resources/css/checkOrder.css
Labels: fix👾

#119 feat: kakaoLogin bug fix
  src/main/webapp/WEB-INF/views/user/userSelect.jsp
Labels: fix👾

#120 fix: 메인페이지 배너 에러 수정
  src/main/webapp/WEB-INF/views/avg.jsp
  src/main/webapp/WEB-INF/views/book/mainpage.jsp
  src/main/webapp/WEB-INF/views/layout/banner.jsp
  src/main/webapp/resources/css/banner.css
  src/main/webapp/resources/css/header.css
Labels: fix👾, hotfix🚨

#122 fix: 통계페이지 오류 수정
  src/main/java/bossbabies/com/a/controller/AvgController.java
  src/main/webapp/WEB-INF/views/avg.jsp
Labels: fix👾, hotfix🚨
